### ISSUE TITLE
how to use --scale_overide command for this converter.exe

### ISSUE THREAD

**Issue by ranjeetborntowin** [gdamoreira/google-ar-asset-converter#14]
Whenever i am trying to use --scale_overide command the exe stops working.
Can you please tell me how to use this command to override the scaling value of my files?

**Comment by ManuelTS** [comment]
Have you tried `--scale_override`, since your command misses an `r`? But I guess it is just a typo here.

Two questions:
1. From where do you know that there is such an argument?
1. Is there somewhere a list of arguments from converter?

I suggest to provide a link or direct the list of arguments inside the `README` for `converter` or `matc`.

I'm asking this two questions since I'm getting messages as

```
Warning: Imported asset was very small (3.9 x 3.0 x 2.4 cm)
         Setting scale to: 1.29 to compensate
```
And I do not need any compensation.

/Edit: I figured it out myself, and I created a pull request #15 .

I'm experiencing the same error with `--scale_override 1` or  `--scale_override 1.0`, I tried to set this values for no scalling at all

**Comment by gdamoreira** [comment]
Hi @ranjeetborntowin @ManuelTS, I don't have an answer about the `--scale_override`. Please refer to the GoogleAR repo to found answers about this bug.

https://github.com/google-ar/sceneform-android-sdk/issues

Thanks

**Comment by ranjeetborntowin** [comment]
It is working now for the latest converter.exe you have just uploaded.
I just need to provide the scaling value against the command argument like this :./sceneform_sdk/windows/converter -a -d --mat ./sceneform_sdk/default_materials/obj_material.sfm --outdir ./output/ ./input/andy.obj --scale_override 2.0
Generated sfa,sfb will be in the given scaling value.

Thanks.

**Comment by gdamoreira** [comment]
Great news @ranjeetborntowin! I'm closing this issue!
